apiVersion: v1
kind: Service
metadata:
  name: my-go-app-svc
  labels:
          app: my-go-app
spec:
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32003
  type: NodePort
